// src/context/Snack/providers/SnackProvider.tsx
import {
  useCallback,
  useEffect,
  useMemo,
  useRef,
  useState,
  type JSX,
  type ReactNode,
} from 'react';
import CheckCircleIcon from '@mui/icons-material/CheckCircle';
import CloseIcon from '@mui/icons-material/Close';
import ErrorIcon from '@mui/icons-material/Error';
import InfoIcon from '@mui/icons-material/Info';
import WarningIcon from '@mui/icons-material/Warning';
import Alert from '@mui/material/Alert';
import Box from '@mui/material/Box';
import Fade from '@mui/material/Fade';
import IconButton from '@mui/material/IconButton';
import { type Theme } from '@mui/material/styles';
import Typography from '@mui/material/Typography';

import { generateRuntimeId } from '@/utils/crypto';
import {
  ANIMATION_DURATION,
  SNACK_DISPLAY_DURATION,
  SNACKS,
} from '../constants/snackConstants';
import { SnackContext } from '../context/SnackContext';

import type { SnackContextProps, SnackSeverity } from '../types/snackTypes';

/**
 * Structural contract defining properties expected by the global snack notification coordinator.
 */
interface SnackProviderProps {
  /** The composite React element node children nested within the visual alert system tree */
  readonly children: ReactNode;
}

/**
 * Structural contract representing a singular instantiated snack message metadata layer with lifecycle state flags for exit transitions.
 */
interface RenderableSnackItem {
  /** The unique identifier generated by infrastructure utilities for stack clearing */
  readonly id: string;
  /** The text string content visible to the user inside the alert box */
  readonly message: string;
  /** The specific severity class style token routing color palettes */
  readonly severity: SnackSeverity;
  /** Explicit indicator flag tracking whether the visual notification node is currently undergoing a decay transition */
  readonly isExiting: boolean;
}

const SNACK_MUI_ICON_MAP = {
  [SNACKS.SUCCESS]: CheckCircleIcon,
  [SNACKS.ERROR]: ErrorIcon,
  [SNACKS.INFO]: InfoIcon,
  [SNACKS.WARNING]: WarningIcon,
} as const;

/**
 * Context Provider managing a coordinated floating notification alert queue via Material UI tokens.
 * Orchestrates structural state arrays, handles unmounting transitions, and safely disposes background garbage collection timeouts.
 */
export const SnackProvider = ({
  children,
}: SnackProviderProps): JSX.Element => {
  const [snacks, setSnacks] = useState<readonly RenderableSnackItem[]>([]);

  const isMountedRef = useRef(true);
  const timersRef = useRef<Map<string, ReturnType<typeof setTimeout>>>(
    new Map()
  );

  useEffect(() => {
    isMountedRef.current = true;
    const currentTimers = timersRef.current;

    return () => {
      isMountedRef.current = false;
      currentTimers.forEach((timer) => clearTimeout(timer));
      currentTimers.clear();
    };
  }, []);

  const removeSnackFromDOM = useCallback((id: string): void => {
    setSnacks((prev) => prev.filter((snack) => snack.id !== id));
    timersRef.current.delete(id);
  }, []);

  const dismissSnack = useCallback(
    (id: string): void => {
      setSnacks((prev) => {
        const target = prev.find((s) => s.id === id);

        if (!target || target.isExiting) return prev;

        const pendingTimer = timersRef.current.get(id);

        if (pendingTimer) {
          clearTimeout(pendingTimer);
          timersRef.current.delete(id);
        }

        if (!isMountedRef.current) return prev;

        const animationTimer = setTimeout(() => {
          removeSnackFromDOM(id);
        }, ANIMATION_DURATION);

        timersRef.current.set(id, animationTimer);

        return prev.map((snack) =>
          snack.id === id ? { ...snack, isExiting: true } : snack
        );
      });
    },
    [removeSnackFromDOM]
  );

  const pushSnack = useCallback(
    (message: string, severity: SnackSeverity): void => {
      if (!isMountedRef.current) return;

      const id = generateRuntimeId();

      setSnacks((prev) => [
        ...prev,
        { id, message, severity, isExiting: false },
      ]);

      const timer = setTimeout(() => {
        dismissSnack(id);
      }, SNACK_DISPLAY_DURATION);

      timersRef.current.set(id, timer);
    },
    [dismissSnack]
  );

  const showSuccessSnack = useCallback(
    (message: string): void => {
      pushSnack(message, SNACKS.SUCCESS);
    },
    [pushSnack]
  );
  const showWarningSnack = useCallback(
    (message: string): void => {
      pushSnack(message, SNACKS.WARNING);
    },
    [pushSnack]
  );
  const showErrorSnack = useCallback(
    (message: string): void => {
      pushSnack(message, SNACKS.ERROR);
    },
    [pushSnack]
  );
  const showInfoSnack = useCallback(
    (message: string): void => {
      pushSnack(message, SNACKS.INFO);
    },
    [pushSnack]
  );

  const contextValue = useMemo<SnackContextProps>(
    () => ({
      showSuccessSnack,
      showWarningSnack,
      showErrorSnack,
      showInfoSnack,
    }),
    [showSuccessSnack, showWarningSnack, showErrorSnack, showInfoSnack]
  );

  const notificationsWrapperStyles = {
    position: 'fixed',
    bottom: { xs: 16, sm: 24 },
    right: { xs: 16, sm: 24 },
    zIndex: (theme: Theme) => theme.zIndex.snackbar,
    display: 'flex',
    flexDirection: 'column',
    gap: 1.5,
    width: '100%',
    maxWidth: 380,
    pointerEvents: 'none',
  } as const;

  return (
    <SnackContext.Provider value={contextValue}>
      {children}

      <Box
        role="region"
        aria-label="System Notifications"
        aria-live="polite"
        sx={notificationsWrapperStyles}
      >
        {snacks.map((snack) => {
          const IconComponent = SNACK_MUI_ICON_MAP[snack.severity];

          return (
            <Fade
              key={snack.id}
              in={!snack.isExiting}
              timeout={ANIMATION_DURATION}
            >
              <Alert
                severity={snack.severity}
                variant="filled"
                icon={<IconComponent sx={{ fontSize: 20 }} />}
                action={
                  <IconButton
                    size="small"
                    aria-label="Dismiss notification"
                    color="inherit"
                    onClick={() => dismissSnack(snack.id)}
                    sx={{
                      cursor: 'pointer',
                      '&.Mui-focusVisible': {
                        outline: '2px solid',
                        outlineColor: 'common.white',
                        outlineOffset: 2,
                      },
                    }}
                  >
                    <CloseIcon sx={{ fontSize: 16 }} />
                  </IconButton>
                }
                sx={{
                  pointerEvents: 'auto',
                  borderRadius: 2.5,
                  boxShadow: 4,
                  alignItems: 'flex-start',
                  '& .MuiAlert-message': {
                    width: '100%',
                    wordBreak: 'break-word',
                    pt: 0.25,
                  },
                }}
              >
                <Typography
                  variant="body2"
                  sx={{ fontWeight: 600, lineHeight: 1.4 }}
                >
                  {snack.message}
                </Typography>
              </Alert>
            </Fade>
          );
        })}
      </Box>
    </SnackContext.Provider>
  );
};
